global NUMBERS
global _TT_INT
global _TT_FLOAT
global _TT_SUBSTRACT
global _TT_ADD
global _TT_MULT
global _TT_DIV
global _TT_LPARENTHESIS
global _TT_RPARENTHESIS
global _TT_EOF # end of file

# CONSTANT TYPES
NUMBERS = '0123456789'
# TOKENS TYPES
_TT_INT = 'INT'
_TT_FLOAT = 'FLOAT'
_TT_SUBSTRACT = 'SUBSTRACT'
_TT_ADD = 'ADD'
_TT_MULT = 'MULT'
_TT_DIV = 'DIV'
_TT_LPARENTHESIS = 'LPAREN'
_TT_RPARENTHESIS = 'RPAREN'
_TT_EOF = 'EOF'